import { WordDifficulty } from '../../src/types/game.types';
import { insertWords, getTotalWordCount } from '../../src/services/database/WordRepository';
import { generateId } from '../../src/utils/uuid.utils';

const EASY_WORDS = [
  'AGUA','FUEGO','TIERRA','AIRE','SOL','LUNA','ESTRELLA','NUBE','LLUVIA','VIENTO',
  'ÁRBOL','FLOR','HOJA','RAÍZ','SEMILLA','PIEDRA','MONTAÑA','RÍO','MAR','LAGO',
  'PÁJARO','PEZ','LOBO','TIGRE','CABALLO','PERRO','GATO','RATÓN','SERPIENTE','ÁGUILA',
  'CASA','PUERTA','VENTANA','ESCALERA','TECHO','PARED','SUELO','JARDÍN','CAMINO','PUENTE',
  'LIBRO','CARTA','MAPA','LLAVE','ESPEJO','RELOJ','VELA','MESA','SILLA','CAMA',
  'ROJO','AZUL','VERDE','NEGRO','BLANCO','DORADO','PLATA','GRIS','OSCURO','LUZ',
  'AMOR','MIEDO','ALEGRÍA','TRISTEZA','IRA','PAZ','CALMA','FUERZA','DÉBIL','GRANDE',
  'MANO','OJO','BOCA','CABEZA','CORAZÓN','SANGRE','HUESO','PIEL','ALMA','VOZ',
  'DÍA','NOCHE','ALBA','TARDE','INVIERNO','VERANO','OTOÑO','PRIMAVERA','TIEMPO','HORA',
  'ORO','HIERRO','MADERA','CRISTAL','HIELO','VAPOR','SOMBRA','REFLEJO','POLVO','CENIZA',
  'CAMINO','BOSQUE','CUEVA','CAMPO','DESIERTO','ISLA','VOLCÁN','GLACIAR','TORNADO','TORMENTA',
  'NIÑO','MUJER','HOMBRE','ANCIANO','BEBÉ','FAMILIA','AMIGO','ENEMIGO','REY','REINA',
  'ESPADA','ESCUDO','LANZA','ARCO','FLECHA','ARMADURA','CORONA','TRONO','BANDERA','MURO',
  'BARCO','BARCA','REMO','VELA','ANCLA','PUERTO','FARO','OLA','MAREA','CORRIENTE',
  'DRAGÓN','FANTASMA','BRUJA','MAGO','HADA','DUENDE','GIGANTE','ENANO','SIRENA','GRIFO',
  'PAN','AGUA','FUEGO','SAL','MIEL','VENENO','POCIÓN','MEDICINA','HIERBA','FLOR',
  'SUEÑO','PESADILLA','VIGILIA','ÉXTASIS','VISIÓN','ESPEJISMO','ILUSIÓN','REALIDAD','VERDAD','MENTIRA',
  'CAMINO','SENDERO','SENDA','RUTA','DESTINO','REGRESO','PARTIDA','LLEGADA','UMBRAL','PORTAL',
  'CUERVO','LECHUZA','MURCIÉLAGO','ARAÑA','ESCORPIÓN','SAPO','COYOTE','ZORRO','CIERVO','OSO',
  'TELA','HILO','AGUJA','NUDO','LAZO','CADENA','CUERDA','TRAMPA','RED','GANCHO',
  'CANCIÓN','SILENCIO','ECO','SUSURRO','GRITO','LLANTO','RISA','MELODÍA','RITMO','TAMBOR',
  'FUEGO','LLAMA','CHISPA','BRASA','HUMO','TIZÓN','HOGUERA','CALOR','FRÍO','NIEBLA',
  'LUNA','ECLIPSE','COMETA','CONSTELACIÓN','GALAXIA','PLANETA','SATÉLITE','METEORO','AURORA','CENIZA',
  'CESTA','COFRE','BAÚL','CAJA','BOLSA','SACO','URNA','JARRÓN','CUENCO','PLATO',
  'NOMBRE','HISTORIA','LEYENDA','MITO','FÁBULA','CUENTO','PROFECÍA','ORÁCULO','SIGNO','SÍMBOLO',
];

const MEDIUM_WORDS = [
  'DESTINO','AZAR','CAOS','ORDEN','EQUILIBRIO','PARADOJA','CICLO','ESPIRAL','VÓRTICE','ABISMO',
  'TRAICIÓN','LEALTAD','HONOR','VERGÜENZA','CULPA','REDENCIÓN','SACRIFICIO','HERENCIA','LEGADO','MALDICIÓN',
  'LABERINTO','ESPEJO','UMBRAL','PORTAL','NEXO','VÍNCULO','FRACTURA','BRECHA','CONFLUENCIA','DIVERGENCIA',
  'TINIEBLAS','PENUMBRA','CREPÚSCULO','AURORA','OCASO','MEDIODÍA','MEDIANOCHE','ETERNIDAD','INSTANTE','FUGAZ',
  'ALQUIMIA','ARCANISMO','ESOTERISMO','OCULTISMO','MISTICISMO','CHAMANISMO','NIGROMANCIA','ADIVINACIÓN','PROFECÍA','RITUAL',
  'ENCANTAMIENTO','HECHIZO','CONJURO','MALDICIÓN','AMULETO','TALISMÁN','RELIQUIA','ARTEFACTO','RELIGIO','SÍMBOLO',
  'MONARCA','TIRANO','HERALDO','VASALLO','ALQUIMISTA','MERCENARIO','ERMITAÑO','ORÁCULO','AUGUR','VIDENTE',
  'ECLIPSE','SOLSTICIO','EQUINOCCIO','CATACLISMO','APOCALIPSIS','GÉNESIS','ÉXODO','REVELACIÓN','TRÁNSITO','UMBRAL',
  'METAMORFOSIS','TRANSMUTACIÓN','TRANSFORMACIÓN','EVOLUCIÓN','INVOLUCIÓN','DEGENERACIÓN','RESURRECCIÓN','REENCARNACIÓN','TRANSFIGURACIÓN','ASCENSIÓN',
  'FRACTAL','SIMETRÍA','RESONANCIA','VIBRACIÓN','FRECUENCIA','ARMONÍA','DISONANCIA','CACOFONÍA','SINFONÍA','SILENCIO',
  'ABISMO','VACÍO','INFINITO','FINITUD','LÍMITE','FRONTERA','HORIZONTE','PERSPECTIVA','PUNTO','LÍNEA',
  'LEGIÓN','COFRADÍA','HERMANDAD','CLAN','TRIBU','LINAJE','ESTIRPE','SANGRE','PACTO','ALIANZA',
  'CENIZA','ESCOMBRO','RUINA','VESTIGIO','HUELLA','RASTRO','RELIQUIA','FRAGMENTO','SHARD','ASTILLA',
  'HAMBRE','SACIEDAD','SED','ANSIA','CODICIA','ENVIDIA','LUJURIA','AVARICIA','PEREZA','SOBERBIA',
  'TRANCE','MEDITACIÓN','CONTEMPLACIÓN','INTROSPECCIÓN','REVELACIÓN','ILUMINACIÓN','EPIFANÍA','INTUICIÓN','PRESENTIMIENTO','PREMONICIÓN',
  'DUALIDAD','TRINIDAD','CUATERNARIO','PENTAGRAMA','HEXAGRAMA','HEPTÁGONO','OCTÓGONO','NONÁGONO','DECÁGONO','ICOSAEDRO',
  'FÉNIX','QUIMERA','BASILISCO','HIDRA','WYVERN','LEVIATÁN','BEHEMOT','KRAKEN','MANTICORA','ESFINGE',
  'DILUVIO','SEQUÍA','HAMBRUNA','PLAGA','PANDEMIA','ÉXODO','MIGRACIÓN','CONQUISTA','LIBERACIÓN','RENDICIÓN',
  'CÓDIGO','CIFRA','RUNA','JEROGLÍFICO','GRIMORIO','PERGAMINO','TOMO','CRÓNICA','ANALES','REGISTRO',
  'CATEDRAL','TEMPLO','SANTUARIO','CRIPTA','MAUSOLEO','ALTAR','OBELISCO','PIRÁMIDE','ZIGURAT','DOLMEN',
  'HERIDA','CICATRIZ','FRACTURA','QUEBRANTO','DESGARRO','TRAUMA','HEMATOMA','LLAGA','ÚLCERA','GANGRENA',
  'VÓRTICE','REMOLINO','TORBELLINO','HURACÁN','CICLÓN','TIFÓN','MONZÓN','NEVADA','GRANIZO','AGUACERO',
  'CREPÚSCULO','OCASO','AMANECER','ALBORADA','MEDIODÍA','MEDIANOCHE','HORA BRUJA','MOMENTO','INSTANTE','ETERNIDAD',
  'UMBRAL','PUERTA','PORTÓN','VENTANA','CELOSÍA','GRIETA','FISURA','HENDIDURA','RENDIJA','ABERTURA',
  'ESPECTRO','APARICIÓN','ECTOPLASMA','WRAITH','BANSHEE','POLTERGEIST','SUCCUBUS','ÍNCUBO','DAEMON','ELDRITCH',
];

const HARD_WORDS = [
  'APOFENIA','PAREIDOLIA','SIMULACRO','SIMULACRUM','APÓCRIFO','PALIMPSESTO','EXÉGESIS','HERMENÉUTICA','SEMIÓTICA','ONTOLOGÍA',
  'ANTINOMIA','APORÍA','TAUTOLOGÍA','SOFISMA','PARALOGISMO','SILOGISMO','DIALÉCTICA','HEURÍSTICA','ABDUCCIÓN','INFERENCIA',
  'CATARSIS','ANAGNÓRISIS','HAMARTIA','PERIPECIA','PARABASIS','ÉXODOS','PRÓLOGO','EPÍLOGO','DEUS EX MACHINA','ÉCFRASIS',
  'TRANSMUTACIÓN','ALOTROPÍA','CATÁLISIS','ÓSMOSIS','DIFUSIÓN','SUBLIMACIÓN','IONIZACIÓN','ELECTRÓLISIS','OXIDACIÓN','REDUCCIÓN',
  'NECRÓPOLIS','CENOTAFIO','CATAFALCO','SARCÓFAGO','OSARIO','NICHO','PANTEÓN','MAUSOLEO','CATACUMBA','CRIPTA',
  'ACÉFALO','ANFIBÓLICO','ANTINÓMICO','APOCATÁSTASIS','APÓSTATA','ARCANO','ARGOT','ARÚSPICE','AUGUR','AUTÓCTONO',
  'BARDO','BILOCACIÓN','BLASFEMIA','BRICOLAJE','CATÉQUESIS','CAUSALIDAD','CENOTAFIO','CHARISMA','CISMÁTICA','CLEMENCIA',
  'DEMIURGO','DEONTOLOGÍA','DIATRIBE','DISONANCIA','DOGMA','DUELO','EIDOLON','EKPYROSIS','ELEUSIS','EMANACIÓN',
  'ENTROPY','ESOTERISMO','ESTRATAGEMA','EURISTÍA','EXCARNACIÓN','EXPIACIÓN','ÉXTASIS','FATALISMO','FETICHE','FLUXUS',
  'GNOSIS','GRIMORIO','HERÉTICO','HIEROFANÍA','HIPERREALIDAD','HOLISMO','HUBRIS','ICONOCLASIA','IDOLOCLASTA','IGNEO',
  'INFRAMUNDO','INITIUM','ISONÓMICA','JEROGLÍFICO','KARMA','KATABASIS','KÉNOSIS','KOAN','KUNDALINI','LABERÍNTICO',
  'LEMNISCATA','LIMINIDAD','LITURGIA','LOGOCENTRISMO','MAGIA SIMPÁTICA','MANDALA','MANTRA','MEMENTO MORI','METEMPSICOSIS','MIASMA',
  'MÍMESIS','MNÉMOSINE','MOIRA','MOMENTO','NEMESIS','NEUMÁTICA','NIHILISMO','NUMINOSO','OCULTISMO','OFRENDA',
  'ÓNFALO','ORÁCULO','OUROBOROS','PALINGENESIA','PANTEÍSMO','PANTOCRÁTOR','PARÁBOLA','PARSIMONIA','PÁTHOS','PENITENCIA',
  'PETICIÓN','PNEUMA','POLITEÍSMO','PRAGMATISMO','PRAXIS','PREFIGURACIÓN','PRESAGIO','PROFANO','PROPICIATORIO','PROSTERNACIÓN',
  'PSICOPOMPO','PURGATORIO','OUIJA','QUEIMADA','QUIMERA','RECAPITULACIÓN','REDENCIÓN','RELICARIO','RELIGIO','RENACIMIENTO',
  'RITO','SACERDOCIO','SAGRADO','SACRIFICIO','SACRILEGIO','SINCRETISMO','SINÉCDOQUE','SOMBRA','SUPREMACÍA','SYMBOLA',
  'TABÚ','TALISMAN','TANATOS','TAROT','TELÚRICO','TEOCRACIA','TEURGIA','THAUMATURGO','TOTEMISMO','UMBRA',
  'VATICINIO','VENERACIÓN','VIGILIA','VISIONARIO','VÓRTICE','XENOFILIA','XENOFOBIA','YOGA','ZARATHUSTRA','ZOROASTRISMO',
  'CARONTE','ORFEO','PERSÉFONE','ESTIGIA','TÁRTARO','ELÍSEO','HADES','HERMES','PSIQUE','ANANKÉ',
];

const INFERNAL_WORDS = [
  'APOCATÁSTASIS','ACATALEPSIA','ACÉFALO','ACRIBIA','ADUMBRACIÓN','AENIGMA','AETERNITAS','AEVUM','AGNOSIA','AGONÍA',
  'ALEATORIEDAD','ALGIDEZ','ALIENACIÓN','ALOGÍA','ALOPATÍA','AMBIVALENCIA','AMIMIA','ANACRÓNICO','ANAGOGIA','ANALOGÍA',
  'ANDROFAGIA','ÁNIMA','ANIMISMO','ANIQUILACIÓN','ANOMÍA','ANTINOMIA','ANTROPOFAGIA','APOFATISMO','APOFONÍA','APORÍA',
  'APOTROPAICO','ARCONTE','ASTENIA','ATELOFOBIA','ATROPOS','AUTOFAGIA','BAALZEBUL','BARADUR','BASILISCO','BATRACOMORFO',
  'BELIAL','BIBLIOMANCIA','BIFURCACIÓN','BLASFEMIA','CATOPTROMANCIA','CAUSALIDAD','CHTHÓNICO','CLARIVIDENCIA','CREPITACIÓN','CRYPTOMNESIA',
  'DEMONOLOGÍA','DENDROLATRÍA','DEONTOLOGÍA','DESTIERRO','DIAFONÍA','DIALEXIS','DISOLUCIÓN','DISSONANTIA','DOGMATISMO','DRUIDA',
  'DUENDE','ECTOPLASMIA','EIDOLON','EINHERJAR','EKATOMBE','EKPYROSIS','ELDRITCH','EMANATISMO','ENEADA','ENTALPÍA',
  'ENTROPÍA','EPIFENÓMENO','EPOPTÍA','ESCATOLOGÍA','ESOTÉRICA','ÉTER','ETHOS','EUHEMERISMO','EXERGASIA','EXSUFFLATION',
  'FATALISMO','FETICHISMO','FLATUS VOCIS','FORTUNA','FULGURACIÓN','GALDR','GNÓMICA','GOETIA','GRIMOIRE','HAMARTIA',
  'HECATOMBE','HEDONISMO','HÉGIRA','HEIMARMENE','HERESIARCA','HERÉTICO','HETERODOXIA','HIEROFANTE','HIEROGAMIA','HIPOSTASIS',
  'HOLOGRAFÍA','HOMONOIA','HUBRIS','HYPNAGOGIA','HYPNOPOMPIA','IDOLOCLASIA','IDOLATRÍA','IMMANENCIA','INEFABILIDAD','INICIACIÓN',
  'INSONDABLE','INTERSTICIO','INVOLUCIÓN','ISOPSEPHIA','KABBALAH','KAKODEMON','KATÁBASIS','KENOMA','KLESIS','KYKEON',
  'LECANOMANCIA','LEMÚRICA','LICANTROPIA','LOGOMANCY','LUCIFUGUS','MACABRO','MAGNUM OPUS','MALEFICA','MALÉFICO','MALEFICIUM',
  'MANICHEO','MAZMORRA','MEGALOMANIA','METEMPSICOSIS','MILENARISMOS','MIMICRY','MNEMONICÓN','MOIRA','MONISMO','MYTHOPOEIA',
  'NECROLATRÍA','NECROMANCER','NEFANDISMO','NOÚMENO','NUGATORIO','NUMINOSIDAD','OBLITERACIÓN','OCLOCRACIA','OFIDISMO','ONOMATOMANCIA',
  'ONTOMAQUIA','ORFISMO','ÓRGASMUS','ORGIASMUS','OUROBOROS','PALINGENESIA','PANPSIQUISMO','PARACELSO','PARASITISMO','PAREIDOLIA',
  'PAROEMIA','PENUMBRA','PETICIÓN','PHARMAKOS','PLEROSIS','PNEUMATOLOGÍA','POLIMORFISMO','PRESENCIA','PSICAGOGIA','PSICOPOMPO',
  'PSICOSTASIA','THERIOMORFISMO','TANATOPRAXIS','TANTRISMO','TAUMATURGIA','TELEQUINESIA','TEOFAGIA','TEOMAQUIA','THANATOS','THELEMA',
  'TRANSMOGRIFICACIÓN','TREPANACIÓN','UMBRA MUNDI','UNHEIMLICH','UROBORO','VACUIDAD','VAMPIRISMO','VESPERAL','VIGILIA MORTIS','VORTICISM',
  'XENOGLOSIA','XIFOPAGO','YALDABAOTH','YETZER HARA','ZEITGEIST','ZOANTROPÍA','ZOMBIFICACIÓN','ZOÓLATRA','ZOOMORFISMO','ZYXOMMA',
];

function buildWords(texts: string[], difficulty: WordDifficulty) {
  return texts.map((text) => ({
    id: generateId(),
    text,
    difficulty,
    language: 'es',
  }));
}

export async function seedWords(): Promise<void> {
  const total = await getTotalWordCount();
  if (total > 0) return;

  const words = [
    ...buildWords(EASY_WORDS, 'EASY'),
    ...buildWords(MEDIUM_WORDS, 'MEDIUM'),
    ...buildWords(HARD_WORDS, 'HARD'),
    ...buildWords(INFERNAL_WORDS, 'INFERNAL'),
  ];

  await insertWords(words);
}
