import { DifficultyConfig, SoloDifficultyId } from '../types/solo.types';
import { WordDifficulty } from '../../../types/game.types';

export const DIFFICULTY_CONFIGS: Record<SoloDifficultyId, DifficultyConfig> = {
  apprentice: {
    id: 'apprentice',
    label: 'APRENDIZ',
    description: 'Relaciones directas. Para iniciados en el ritual.',
    minTargetWords: 2,
    maxTargetWords: 4,
    preferredTargetSizes: [3, 2, 4],
    minimumRelationStrength: 0.55,
    minimumIndividualRelation: 0.50,
    maximumRisk: 0.35,
    maximumRivalRisk: 0.22,
    maximumNeutralRisk: 0.22,
    maximumCursedRisk: 0.14,
    maximumAbstraction: 0.25,
    minimumCommonness: 0.85,
    minimumFamiliarity: 0.90,
    maximumTechnicality: 0.05,
    maximumRegionality: 0.05,
    allowSecondaryRelations: false,
    allowSimpleMetaphors: false,
    primaryCategoryWeight: 1.0,
    secondaryCategoryWeight: 0.3,
    formalVocabularyWeight: 0.0,
    timeMultiplier: 1.2,
    scoreMultiplier: 1.0,
    unlockRequirement: { unlockedByDefault: true },
  },

  initiated: {
    id: 'initiated',
    label: 'INICIADO',
    description: 'Relaciones primarias y secundarias. Distractores moderados.',
    minTargetWords: 2,
    maxTargetWords: 4,
    preferredTargetSizes: [3, 2, 4],
    minimumRelationStrength: 0.45,
    minimumIndividualRelation: 0.42,
    maximumRisk: 0.45,
    maximumRivalRisk: 0.28,
    maximumNeutralRisk: 0.28,
    maximumCursedRisk: 0.18,
    maximumAbstraction: 0.35,
    minimumCommonness: 0.75,
    minimumFamiliarity: 0.85,
    maximumTechnicality: 0.08,
    maximumRegionality: 0.08,
    allowSecondaryRelations: true,
    allowSimpleMetaphors: false,
    primaryCategoryWeight: 0.85,
    secondaryCategoryWeight: 0.55,
    formalVocabularyWeight: 0.1,
    timeMultiplier: 1.0,
    scoreMultiplier: 1.4,
    unlockRequirement: {
      unlockedByDefault: false,
      requiredWinsInPreviousLevel: 5,
      minimumAverageAccuracy: 0.55,
    },
  },

  medium: {
    id: 'medium',
    label: 'MEDIUM',
    description: 'Relaciones conceptuales. Conecta hasta cuatro almas.',
    minTargetWords: 2,
    maxTargetWords: 4,
    preferredTargetSizes: [3, 2, 4],
    minimumRelationStrength: 0.35,
    minimumIndividualRelation: 0.34,
    maximumRisk: 0.55,
    maximumRivalRisk: 0.34,
    maximumNeutralRisk: 0.34,
    maximumCursedRisk: 0.22,
    maximumAbstraction: 0.48,
    minimumCommonness: 0.65,
    minimumFamiliarity: 0.80,
    maximumTechnicality: 0.10,
    maximumRegionality: 0.10,
    allowSecondaryRelations: true,
    allowSimpleMetaphors: true,
    primaryCategoryWeight: 0.70,
    secondaryCategoryWeight: 0.75,
    formalVocabularyWeight: 0.25,
    timeMultiplier: 0.9,
    scoreMultiplier: 2.0,
    unlockRequirement: {
      unlockedByDefault: false,
      requiredWinsInPreviousLevel: 8,
      minimumAverageAccuracy: 0.65,
    },
  },

  nightmare: {
    id: 'nightmare',
    label: 'PESADILLA',
    description: 'Asociaciones indirectas. Más distractores. Riesgo elevado.',
    minTargetWords: 2,
    maxTargetWords: 4,
    preferredTargetSizes: [3, 2, 4],
    minimumRelationStrength: 0.28,
    minimumIndividualRelation: 0.28,
    maximumRisk: 0.65,
    maximumRivalRisk: 0.42,
    maximumNeutralRisk: 0.42,
    maximumCursedRisk: 0.28,
    maximumAbstraction: 0.62,
    minimumCommonness: 0.55,
    minimumFamiliarity: 0.75,
    maximumTechnicality: 0.10,
    maximumRegionality: 0.10,
    allowSecondaryRelations: true,
    allowSimpleMetaphors: true,
    primaryCategoryWeight: 0.55,
    secondaryCategoryWeight: 0.90,
    formalVocabularyWeight: 0.45,
    timeMultiplier: 0.75,
    scoreMultiplier: 3.0,
    unlockRequirement: {
      unlockedByDefault: false,
      requiredWinsInPreviousLevel: 10,
      minimumAverageAccuracy: 0.72,
    },
  },

  hell: {
    id: 'hell',
    label: 'INFIERNO',
    description: 'Relaciones abstractas. Vocabulario culto. Solo para elegidos.',
    minTargetWords: 2,
    maxTargetWords: 4,
    preferredTargetSizes: [3, 2, 4],
    minimumRelationStrength: 0.20,
    minimumIndividualRelation: 0.24,
    maximumRisk: 0.75,
    maximumRivalRisk: 0.48,
    maximumNeutralRisk: 0.48,
    maximumCursedRisk: 0.32,
    maximumAbstraction: 0.75,
    minimumCommonness: 0.45,
    minimumFamiliarity: 0.70,
    maximumTechnicality: 0.10,
    maximumRegionality: 0.10,
    allowSecondaryRelations: true,
    allowSimpleMetaphors: true,
    primaryCategoryWeight: 0.40,
    secondaryCategoryWeight: 1.0,
    formalVocabularyWeight: 0.80,
    timeMultiplier: 0.6,
    scoreMultiplier: 5.0,
    unlockRequirement: {
      unlockedByDefault: false,
      requiredWinsInPreviousLevel: 12,
      minimumAverageAccuracy: 0.78,
    },
  },
};

/** Mapea dificultad del modo solitario a dificultad de palabras del tablero */
export const SOLO_TO_WORD_DIFFICULTY: Record<SoloDifficultyId, WordDifficulty> = {
  apprentice: 'EASY',
  initiated:  'EASY',
  medium:     'MEDIUM',
  nightmare:  'HARD',
  hell:       'INFERNAL',
};

export const DIFFICULTY_ORDER: SoloDifficultyId[] = [
  'apprentice', 'initiated', 'medium', 'nightmare', 'hell',
];

export function getPreviousDifficulty(id: SoloDifficultyId): SoloDifficultyId | null {
  const idx = DIFFICULTY_ORDER.indexOf(id);
  return idx > 0 ? DIFFICULTY_ORDER[idx - 1] : null;
}
