import { ImageSourcePropType } from 'react-native';

export const createMatchAssets = {
  background: {
    underworld: require('../../assets/screens/create-match/01_background/background_create_match_underworld.png') as ImageSourcePropType,
  },
  frame: {
    screen: require('../../assets/screens/create-match/02_screen_frame/frame_screen_ritual_create_match.png') as ImageSourcePropType,
  },
  portal: {
    arch: require('../../assets/screens/create-match/03_portal_layer/background_arch_portal_empty.png') as ImageSourcePropType,
  },
  decorations: {
    hourglassLeft: require('../../assets/screens/create-match/04_decorations/hourglass_left.png') as ImageSourcePropType,
    hourglassRight: require('../../assets/screens/create-match/04_decorations/hourglass_right.png') as ImageSourcePropType,
    book: require('../../assets/screens/create-match/04_decorations/book_ritual_open.png') as ImageSourcePropType,
  },
  difficulty: {
    panel: require('../../assets/screens/create-match/05_top_difficulty_panel/panel_difficulty_empty.png') as ImageSourcePropType,
  },
  characters: {
    medium: require('../../assets/screens/create-match/06_characters/character_medium_dual_energy.png') as ImageSourcePropType,
    spiritBlue: require('../../assets/screens/create-match/06_characters/spirit_blue_lower.png') as ImageSourcePropType,
    spiritRed: require('../../assets/screens/create-match/06_characters/spirit_red_lower.png') as ImageSourcePropType,
  },
  timerPanels: {
    medium: require('../../assets/screens/create-match/07_timer_panels/panel_timer_medium_empty.png') as ImageSourcePropType,
    interpreters: require('../../assets/screens/create-match/07_timer_panels/panel_timer_interpreters_empty.png') as ImageSourcePropType,
  },
  segmentedOptions: {
    inactive: require('../../assets/screens/create-match/08_segmented_options/segmented_option_inactive.png') as ImageSourcePropType,
    active: require('../../assets/screens/create-match/08_segmented_options/segmented_option_active.png') as ImageSourcePropType,
    pressed: require('../../assets/screens/create-match/08_segmented_options/segmented_option_pressed.png') as ImageSourcePropType,
  },
  teamPanel: {
    panel: require('../../assets/screens/create-match/09_team_panel/panel_team_selector_empty.png') as ImageSourcePropType,
  },
  teamOptions: {
    inactive: require('../../assets/screens/create-match/10_team_options/team_option_inactive.png') as ImageSourcePropType,
    blueActive: require('../../assets/screens/create-match/10_team_options/team_option_blue_active.png') as ImageSourcePropType,
    redActive: require('../../assets/screens/create-match/10_team_options/team_option_red_active.png') as ImageSourcePropType,
    randomActive: require('../../assets/screens/create-match/10_team_options/team_option_random_active.png') as ImageSourcePropType,
  },
  primaryButton: {
    inactive: require('../../assets/screens/create-match/11_primary_button/button_primary_start_inactive.png') as ImageSourcePropType,
    active: require('../../assets/screens/create-match/11_primary_button/button_primary_start_active.png') as ImageSourcePropType,
    pressed: require('../../assets/screens/create-match/11_primary_button/button_primary_start_pressed.png') as ImageSourcePropType,
    disabled: require('../../assets/screens/create-match/11_primary_button/button_primary_start_disabled.png') as ImageSourcePropType,
  },
  iconButtons: {
    backInactive: require('../../assets/screens/create-match/12_icon_buttons/button_icon_back_inactive.png') as ImageSourcePropType,
    backPressed: require('../../assets/screens/create-match/12_icon_buttons/button_icon_back_pressed.png') as ImageSourcePropType,
    settingsInactive: require('../../assets/screens/create-match/12_icon_buttons/button_icon_settings_inactive.png') as ImageSourcePropType,
    settingsPressed: require('../../assets/screens/create-match/12_icon_buttons/button_icon_settings_pressed.png') as ImageSourcePropType,
  },
  icons: {
    difficultyEasyInactive: require('../../assets/screens/create-match/13_icons/difficulty_icon_easy_inactive.png') as ImageSourcePropType,
    difficultyEasyActive: require('../../assets/screens/create-match/13_icons/difficulty_icon_easy_active.png') as ImageSourcePropType,
    difficultyMediumInactive: require('../../assets/screens/create-match/13_icons/difficulty_icon_medium_inactive.png') as ImageSourcePropType,
    difficultyMediumActive: require('../../assets/screens/create-match/13_icons/difficulty_icon_medium_active.png') as ImageSourcePropType,
    difficultyHardInactive: require('../../assets/screens/create-match/13_icons/difficulty_icon_hard_inactive.png') as ImageSourcePropType,
    difficultyHardActive: require('../../assets/screens/create-match/13_icons/difficulty_icon_hard_active.png') as ImageSourcePropType,
    difficultyInfernalInactive: require('../../assets/screens/create-match/13_icons/difficulty_icon_infernal_inactive.png') as ImageSourcePropType,
    difficultyInfernalActive: require('../../assets/screens/create-match/13_icons/difficulty_icon_infernal_active.png') as ImageSourcePropType,
    teamBlue: require('../../assets/screens/create-match/13_icons/icon_team_blue.png') as ImageSourcePropType,
    teamRed: require('../../assets/screens/create-match/13_icons/icon_team_red.png') as ImageSourcePropType,
    teamRandom: require('../../assets/screens/create-match/13_icons/icon_team_random.png') as ImageSourcePropType,
  },
} as const;

export const createMatchAssetList: ImageSourcePropType[] = [
  createMatchAssets.background.underworld,
  createMatchAssets.frame.screen,
  createMatchAssets.portal.arch,
  createMatchAssets.decorations.hourglassLeft,
  createMatchAssets.decorations.hourglassRight,
  createMatchAssets.decorations.book,
  createMatchAssets.difficulty.panel,
  createMatchAssets.characters.medium,
  createMatchAssets.characters.spiritBlue,
  createMatchAssets.characters.spiritRed,
  createMatchAssets.timerPanels.medium,
  createMatchAssets.timerPanels.interpreters,
  createMatchAssets.segmentedOptions.inactive,
  createMatchAssets.segmentedOptions.active,
  createMatchAssets.segmentedOptions.pressed,
  createMatchAssets.teamPanel.panel,
  createMatchAssets.teamOptions.inactive,
  createMatchAssets.teamOptions.blueActive,
  createMatchAssets.teamOptions.redActive,
  createMatchAssets.teamOptions.randomActive,
  createMatchAssets.primaryButton.inactive,
  createMatchAssets.primaryButton.active,
  createMatchAssets.primaryButton.pressed,
  createMatchAssets.primaryButton.disabled,
  createMatchAssets.iconButtons.backInactive,
  createMatchAssets.iconButtons.backPressed,
  createMatchAssets.iconButtons.settingsInactive,
  createMatchAssets.iconButtons.settingsPressed,
  createMatchAssets.icons.difficultyEasyInactive,
  createMatchAssets.icons.difficultyEasyActive,
  createMatchAssets.icons.difficultyMediumInactive,
  createMatchAssets.icons.difficultyMediumActive,
  createMatchAssets.icons.difficultyHardInactive,
  createMatchAssets.icons.difficultyHardActive,
  createMatchAssets.icons.difficultyInfernalInactive,
  createMatchAssets.icons.difficultyInfernalActive,
  createMatchAssets.icons.teamBlue,
  createMatchAssets.icons.teamRed,
  createMatchAssets.icons.teamRandom,
];
